### ISSUE TITLE
Add scalaz subproject

### ISSUE THREAD

**Issue by vil1** [Kanaka-io/play-monadic-actions#17]
As of 2.0.x we need a new subproject for scalaz compatibility

It should provide at least
- `Functor[Step]` and `Monad[Step]` instances 
- conversions from `B \/ A`, `Future[B \/ A]`, `Validation[A, B]` and `Future[Validation[A, B]]` to `Step[A]`

**Comment by drbild** [comment]
Before release, this should probably be split into separate `scalaz71` and `scalaz72` subprojects.
