### ISSUE TITLE
 support de Seq

### ISSUE THREAD

**Issue by crakjie** [Kanaka-io/play-monadic-actions#3]
Est t'il possible d'avoir un support des listes pour les for comprehension
tel que 

```
for {
        users <- SomeService.getRelatedUsers(id) ?|  NotFound
        user <- users
        _    <- SomeService.performUpdate(user, su) ?| Conflict
} yield NoContent
```

je pensais que quelque chose dans ce bou la : 

```
private [ActionDSL] def fromSeq[A](onEmpty: => Result)(seq: Seq[A]): Step[A] =
    EitherT[Future, Result, A](Future.successful(seq.fold(onEmpty)(x=> x))
```

Mais je ne vois pas comment il serais possible de géré les erreur une a une.

**Comment by vil1** [comment]
Hi

There is a fundamental problem with mixing different monads in the same for comprehension (for a more detailed discussion, please take a look at [the slides](https://kanaka-io.github.io/play-monadic-actions/index.html) ).
Moreover, in the context of an action, you want to yield a single response, so the non-determinism introduced by the `List` monad is not suitable for that matter.
A more satisfying solution would be to push this responsibility down on the service layer by defining a `SomeService.performUpdates` method that would take a list of users to update. Additionally, this method could use `scalaz.ValidationNel` to aggregate all the possible errors that could occur during the updates.

**Comment by crakjie** [comment]
It's a pity for the clarity of the code but I think I understand.
