### ISSUE TITLE
Build failing due to Travis image update

### ISSUE THREAD

**Issue by searler** [Kanaka-io/play-monadic-actions#31]
Same error reported as  https://github.com/travis-ci/travis-ci/issues/7703

**Comment by vil1** [comment]
Good catch, thanks !

Apparently, your PR hits https://github.com/travis-ci/travis-ci/issues/7703.

I'll add the required workaround in the `.travis.yml` in the branch of #30 and make a new PR (I'll also add your name in the contributors list).

Thanks a lot
