### ISSUE TITLE
Play 2.6 compatibility & Scala 2.12

### ISSUE THREAD

**Issue by dgouyette** [Kanaka-io/play-monadic-actions#33]
To allow compatibility with playframework 2.6. It would be necessary to add the cross compilation for scala 2.12

**Comment by vil1** [comment]
That's on my TODO. It might change/simplify some code around `Either` and pals though.
PRs welcome ! :)

**Comment by dgouyette** [comment]
I'll take a look to see what I can do


Le mar. 11 juil. 2017 à 15:12, Valentin Kasas <notifications@github.com> a
écrit :

**Comment by dgouyette** [comment]
PR done, but i didn't do all the cleaning

**Comment by vil1** [comment]
Fixed by #36
