### ISSUE TITLE
Recommended way to recover from failed futures

### ISSUE THREAD

**Issue by mrwillis** [Kanaka-io/play-monadic-actions#39]
Thanks for this library. Really saved me from the pyramid of doom.

How can I recover from failed futures along the for comprehension? For instance, suppose the first future in the comprehension throws an exception. I want this to fail the whole comprehension but I also want to handle the specific exception  and return an appropriate `InternalServerError` or whatever it may be.

Thanks!

**Comment by mrwillis** [comment]
Figured it out. I tried to `recover` the comprehension but realized I was missing parentheses. Has nothing to do with this library

**Comment by vil1** [comment]
Hey @mrwillis, happy to hear you found a solution (and I'm also happy to that this lib is of help to you).
Happy hacking!
