### ISSUE TITLE
Add helpers for ActionBuilder / ActionFunction creation

### ISSUE THREAD

**Issue by vil1** [Kanaka-io/play-monadic-actions#6]

**Comment by drbild** [comment]
@vil1 Do you have an example use for the helpers? Or a type signature for the desired helpers?

**Comment by vil1** [comment]
Damn, I should have written a description when I first created this issue last year : /

@dgouyette any idea what this could be about ?

**Comment by dgouyette** [comment]
No, i don't remember. 😁
